### ISSUE TITLE
After plugin closure... windows remain open.

### ISSUE THREAD

**Issue by etarena** [flimlib/flimlib#25]
1) before 'Fit Curve' selected - when quitting SLIM Curve from the UI panel...  the fitted decay graph remains open.

2) after 'Fit Curve' selected/processed... when quitting SLIM Curve from UI panel...  the fitted decay graph remains open, as well as the histogram tool panel and all fitted image windows.

*\* essentially - only the UI panel and grayscale lifetime image close properly **

(Fiji Is Just) ImageJ 2.0.0-rc-34/1.50a; Java 1.8.0_51 [64-bit]; Mac OS X 10.10.5

**Comment by Xanthorapedia** [comment]
The SLIM Curve plugin for ImageJ has been retired in favor of [FLIMJ](https://imagej.net/FLIMJ).
