### ISSUE TITLE
'Export Pixels/Histograms to Text' -- ImageJ2 UI upgrade

### ISSUE THREAD

**Issue by etarena** [flimlib/flimlib#27]
Currently, when a user wants to 'Export Pixels to Text' or 'Export Histograms to Text' - the default location of created .tsv files is within package contents of Fiji.app unless a specific file path is manually entered by the user.  

*\* Upgrade to ImageJ2 UI to allow user to browse directories, etc. **

**Comment by ctrueden** [comment]
FWIW, the problematic code is [here](https://github.com/slim-curve/slim-plugin/blob/5b12b4f64bd07318a47615b96215892336d706eb/src/main/java/loci/slim/analysis/plugins/ExportPixelsToText.java#L364-L369). And should be updated to use the SciJava `@Parameter` mechanism; see e.g. [widget-demo](https://github.com/imagej/imagej-tutorials/blob/cec6e4d10d9cf066ef9152434295bbebb89e9931/widget-demo/src/main/java/WidgetDemo.java).

**Comment by etarena** [comment]
k.  i think i get it - but don't know how to implement.  yet.

**Comment by Xanthorapedia** [comment]
The SLIM Curve plugin for ImageJ has been retired in favor of [FLIMJ](https://imagej.net/FLIMJ).
