### ISSUE TITLE
Array processing in the C library?

### ISSUE THREAD

**Issue by marktsuchida** [flimlib/flimlib#40]
When using through Python bindings (#39), the slowness of looping in Python becomes an issue, such as when fitting every pixel of a FLIM image.

So I'm wondering if it would make sense for us to add C library functions with array processing capability: basically wrappers around the fitting functions that take many input histograms (as a 2D array), and run the algorithms on each input with the same parameters, producing array outputs that have one extra dimension.

The Java bindings, if I understand correctly, provide looping via Ops, and Java has JIT compilation, so this is probably not directly relevant to most Java use cases.

Before going into details, would you be open to adding such functions, esp. @paulbarber? We (@facetorched and I) will do the work, of course. The alternative would be to have similar C functions hidden in our Python wrapper and only available for use from Python.

**Comment by paulbarber** [comment]
Hi,
I am certainly open to you adding array capability in C. Great to see you adding a direct Python interface to the library!
Cheers,

**Comment by marktsuchida** [comment]
#49 and #50.
