### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by marktsuchida** [flimlib/flimlib#56]
Builds are currently in the process of being migrated to GitHub Actions. This issue is to track this process.

Currently, build fails on Ubuntu due to tests failing. It turns out that the old CI (Travis) was not running the tests (at least not in a way that failed the build), and some of the tests (using cram) don't run on Windows, so we have accumulated some failing tests.

In a few cases it appears that the tests are too numerically stringent, but other failures might indicate real bugs. I am reviewing each test.

**Comment by paulbarber** [comment]
Hi @marktsuchida ,
I do not recall contributing to these test data. Your final sentence captures a very reasonable way forward from my point of view. Thanks.

**Comment by Xanthorapedia** [comment]
Hi @marktsuchida, thanks for looking into this, and thank @paulbarber for replying. I have some rusty memory about how those tests become what they are now. Please see if the following helps:
 
 - `test_files/test.json`: those are from the old `slim-curve/slim-curve-test` provided by @paulbarber as regression tests for `slim-curve/slim-curve` . They are used in conjunction with `flimlib-test` (built from [`test/c/main.c`](https://github.com/flimlib/flimlib/blob/73074513701b2c140ce3799368a25b773ab2e634/src/test/c/main.c)), which parses those configs and runs the verification. At the time we merge `slim-curve/slim-curve-test`, a lot of them (52, to be precise) have failed, and it was not possible to fix them by hand. Knowing whether the failed tests are still failing is probably not as good an indication of behavior change, but it's better than nothing. So we kept the failing tests.
 - `test_files/[original|ref].json`: in the light of the above, we created a new reference point using the following command:
https://github.com/flimlib/flimlib/blob/87451fe71bd88bd8fbeee92084a540b0f33c2c99/tests/flimlib-native-test.t#L9-L10
and kept a template for future tests _("`test.json`" could really be "`ref.json`")_:
https://github.com/flimlib/flimlib/blob/87451fe71bd88bd8fbeee92084a540b0f33c2c99/src/test/c/README.txt#L45
 - `test_files/*.[ini|dat]`: those are the hyperparameters and decay data files for the command line driver, `flimlib-cmd` (built from [src/flimlib-cmd/c/main.c](https://github.com/flimlib/flimlib/blob/87451fe71bd88bd8fbeee92084a540b0f33c2c99/src/flimlib-cmd/c/main.c), not to be confused with `flimlib-test`). Unlike `test_files/*.json`, they are mainly for demonstration purposes and did not come with output expectations. We made them into regression tests by manually recording the output (`transient.dat` seems unused).
 - `flimlib-cmd-cpp`: this is the demo built from [src/flimlib-cmd/cpp/main.cpp](https://github.com/flimlib/flimlib/blob/87451fe71bd88bd8fbeee92084a540b0f33c2c99/src/flimlib-cmd/cpp/main.cpp) to showcase the C++ API. It contains a hardcoded decay fit.
 - `tests/*.t`: those are the Cram scripts that runs the above (`flimlib-test`, `flimlib-cmd`, and `flimlib-cmd-cpp`) and check their outputs. _One thing to note is that Cram does not support Windows, so those tests are skipped when building the Windows binary on AppVeyor._
 - We were able to use some of the existing tests from the old SlimCurve java API and port some others to java ([src/test/java/flimlib/FLIMLib*Test.java](https://github.com/flimlib/flimlib/tree/87451fe71bd88bd8fbeee92084a540b0f33c2c99/src/test/java/flimlib)). Those are the only regression tests for Windows.

Those are all the regression testing mechanisms for this repo as far as I recall. It would be very beneficial if they can get reorganized. I would advocate for the removal of the unuseful tests and re-calibration for those newly failed ones (if the new outputs are reasonable). If one wants to do this more carefully, it may be helpful to run the JUnit tests from its downstream projects, e.g., [flimj-ops](https://github.com/flimlib/flimj-ops), while making it depend on the freshly compiled FLIMLib.

**Comment by marktsuchida** [comment]
Resolved in #57.
