### ISSUE TITLE
Java Install/Build Errors

### ISSUE THREAD

**Issue by nranthony** [flimlib/flimlib#59]
Hi, thanks for your time taken to work on this.

I'm getting an error on running `mvn clean install`, and the same error if I open the project in Netbeans and run clean and build.

`Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (native-cmake-generate) on project flimlib: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]`

See output for more details.
[mvn_clean_install_output.txt](https://github.com/flimlib/flimlib/files/7534205/mvn_clean_install_output.txt)

Thanks
Neil

**Comment by ctrueden** [comment]
@nranthony It looks like something went wrong in the native build handled by cmake. From your log:
```
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring incomplete, errors occurred!
See also "C:/repo/ext/flimlib/target/build/CMakeFiles/CMakeOutput.log".
```
Did you look in the `target/build/CMakeFiles/CMakeOutput.log` to see if there's any further information?

**Comment by nranthony** [comment]
Hi Curtis, thanks for the speedy reply.

output log here
[CMakeOutput.log](https://github.com/flimlib/flimlib/files/7534458/CMakeOutput.log)
Looks like everything went ok; no warnings or errors listed.  It's a fresh OS, and I just installed cmake 3.22.0-rc3

**Comment by ctrueden** [comment]
Hmm, OK, how about running `mvn -X clean install` to get a more verbose Maven log? It might say which command is returning a failing exit code.

**Comment by nranthony** [comment]
Looks like a couple of INFO and WARNING lines, with a whole load of DEBUG, and then some ERRORs at the end.  Hopefully there's something in there to point us in the right direction.
[mvn_x_clean_install_output.txt](https://github.com/flimlib/flimlib/files/7535027/mvn_x_clean_install_output.txt)

I ran `mvn -X clean install > mvn_x_clean_install_output.txt` to grab the output, but still see the below in the cmd line terminal.

```
CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindSWIG.cmake:153 (find_package_handle_standard_args)
  CMakeLists.txt:137 (find_package)
```

Are these cmake errors related, or something that can be ignore?

Thanks

**Comment by ctrueden** [comment]
From the log:
```
[DEBUG] Executing command line: [C:\Program Files\CMake\bin\cmake.exe, c:\repo\ext\flimlib_\flimlib, -DCMAKE_GENERATOR_PLATFORM=x64, -DCMAKE_BUILD_TYPE=Release]
```
:point_up: So that's the command that is failing.

```
  Could NOT find SWIG (missing: SWIG_EXECUTABLE SWIG_DIR)
```
Definitely a problem. SWIG is required to compile this code.

Out of curiosity: why are you trying to build this code yourself, anyway? As opposed to using the prebuilt JARs?

**Comment by nranthony** [comment]
Wonderful, thanks so much for the time.
![image](https://user-images.githubusercontent.com/16306836/141994860-fd7f92f7-25b2-4e6f-b034-5f8be7d5cb73.png)

The reason for the build is half 'just because', and then once the following half knows the first half can be done, I can entertain the idea of adding different minimization algorithms, and/or tweaks/changes.

Again, thanks for your time, your speedy responses and getting me past my problem.

Neil

**Comment by paddyroddy** [comment]
can we add `swig` as an explicit requirement? I fell for this too
