### ISSUE TITLE
how to generate phasor plot ?

### ISSUE THREAD

**Issue by baoyi-A** [flimlib/flimlib#81]
Hi,
I'd like to know how can I make phasor plot from the tiff stack? I couldn'd find the 'a third algorithm' mentioned in 'read me'.

**Comment by JenuC** [comment]
In FLIMJ, you can open the tiff-stack in ImageJ and run the following code in the Script Editor. 
Note the lifetime-axis and x-increment variables in the code, that need to be set.

```
# @ImageJ ij
# @ImgPlus img
op = ij.op()
import flimlib.flimj.FitParams
param = new FitParams()
param.ltAxis = 2; // shows the time axis (for XYT, T=2)
param.xInc = 0.040; // time unit in T-axis
param.transMap = img;
phasorResult = op.run("flim.fitPhasor", param)
phasorResult.paramMap
```

This will generate a new image stack with 6d slices: offset, g, s, tphase, tmod, and avg-tau (in this order). 
Hope this helps.
