### ISSUE TITLE
Provide some sample time-resolved images

### ISSUE THREAD

**Issue by ctrueden** [flimlib/flimlib#9]
It would be nice to provide some public sample images in ICS and SDT formats on the SLIM Curve web site, for use with the SLIM Curve plugin for ImageJ. Such images would be handy for demonstration purposes and testing.

We should not only link to such files on the site, but also show screenshots of them being analyzed so people know what to expect and can reproduce.

Probably the best place for this would be the [SLIM Curve wiki](https://github.com/slim-curve/slim-curve/wiki)...

**Comment by ctrueden** [comment]
Thanks to Paul Barber, the https://scif.io/images/ site now includes [Gray-FLIM-datasets.zip](https://samples.scif.io/Gray-FLIM-datasets.zip), with several sample FLIM datasets in ICS format.

**Comment by JenuC** [comment]
Paul included a FLIM-FRET data set. Thats wonderful.
